"""Concurrent RPC regressions without external providers or timing sleeps."""

import json
import os
import tempfile
import threading
import unittest
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from unittest import mock

from insightkit.data.store import InsightStore
from insightkit.insights.service import InsightService
from insightkit.ipc.server import InsightRPCServer


class ControlledProvider:
    def __init__(self, blocked_model="live-model", fail_first=False):
        self.blocked_model = blocked_model
        self.fail_first = fail_first
        self.entered = threading.Event()
        self.release = threading.Event()
        self.calls = {}
        self._lock = threading.Lock()

    def complete(self, system_prompt, user_prompt, model):
        with self._lock:
            self.calls[model] = self.calls.get(model, 0) + 1
            first_blocked_call = model == self.blocked_model and self.calls[model] == 1
        if first_blocked_call:
            self.entered.set()
            if not self.release.wait(timeout=5):
                raise RuntimeError("test provider was not released")
            if self.fail_first:
                raise RuntimeError("synthetic provider failure")
        return json.dumps({
            "session_overview": {
                "title": model,
                "overview": f"Summary generated by {model}.",
                "topics": [],
            },
            "highlight_insights": [],
            "speaker_perspectives": [],
            "decision_ledger": [],
            "action_tracks": [],
            "timeline_beats": [],
            "provenance_links": [],
        })


class TestInsightConcurrency(unittest.TestCase):
    def setUp(self):
        self.env = mock.patch.dict(os.environ, {"INSIGHTKIT_ANALYSIS_MODE": "cloud"})
        self.env.start()
        self.addCleanup(self.env.stop)
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)

    def make_server(self, provider):
        service = InsightService(provider=provider, default_vendor="test", strict_mode=False)
        server = InsightRPCServer(
            socket_path=Path(self.tmp.name) / "test.sock",
            store=InsightStore(Path(self.tmp.name) / "test.db"),
            insight_service=service,
        )
        self.addCleanup(server.shutdown)
        server.store.upsert_meeting("meeting", "Concurrent summary", "mic", status="recording")
        return server

    @staticmethod
    def dispatch(server, mode, meeting_id="meeting"):
        return server._dispatch({
            "id": mode,
            "method": "insight.refresh_live" if mode == "live" else "insight.build_final",
            "params": {
                "meeting_id": meeting_id,
                "provider_vendor": f"{mode}-vendor",
                "provider_model": f"{mode}-model",
                "strict_mode": mode == "live",
            },
        })

    def assert_summary_meta(self, response, mode):
        self.assertIn("result", response, response)
        result = response["result"]
        self.assertEqual(result["mode"], mode)
        self.assertEqual(result["provider"], f"{mode}-vendor")
        self.assertEqual(result["provider_vendor"], f"{mode}-vendor")
        self.assertEqual(result["provider_model"], f"{mode}-model")
        self.assertEqual(result["strict_mode"], mode == "live")
        self.assertEqual(result["insight_package"]["session_overview"]["title"], f"{mode}-model")

    def test_overlapping_live_requests_return_busy_without_another_provider_call(self):
        provider = ControlledProvider()
        server = self.make_server(provider)
        with ThreadPoolExecutor(max_workers=2) as pool:
            first = pool.submit(self.dispatch, server, "live")
            try:
                self.assertTrue(provider.entered.wait(timeout=1))
                for meeting_id in ("meeting", "another-meeting"):
                    duplicate = pool.submit(self.dispatch, server, "live", meeting_id)
                    response = duplicate.result(timeout=1)
                    self.assertIn("error", response, response)
                    self.assertEqual(response["error"]["code"], -32010)
                    self.assertIn("live_insight_busy", response["error"]["message"])
                    self.assertEqual(provider.calls, {"live-model": 1})
                self.assertFalse(first.done())
            finally:
                provider.release.set()
            self.assert_summary_meta(first.result(timeout=1), "live")

        self.assert_summary_meta(self.dispatch(server, "live"), "live")
        self.assertEqual(provider.calls, {"live-model": 2})

    def test_live_and_final_requests_do_not_block_or_overwrite_each_others_meta(self):
        for blocked_mode, other_mode in (("live", "final"), ("final", "live")):
            with self.subTest(blocked_mode=blocked_mode):
                provider = ControlledProvider(blocked_model=f"{blocked_mode}-model")
                server = self.make_server(provider)
                with ThreadPoolExecutor(max_workers=2) as pool:
                    blocked = pool.submit(self.dispatch, server, blocked_mode)
                    try:
                        self.assertTrue(provider.entered.wait(timeout=1))
                        other = pool.submit(self.dispatch, server, other_mode)
                        self.assert_summary_meta(other.result(timeout=1), other_mode)
                        self.assertFalse(blocked.done())
                    finally:
                        provider.release.set()
                    self.assert_summary_meta(blocked.result(timeout=1), blocked_mode)
                self.assertEqual(provider.calls, {f"{blocked_mode}-model": 1, f"{other_mode}-model": 1})

    def test_failed_live_request_releases_admission_for_the_next_request(self):
        provider = ControlledProvider(fail_first=True)
        server = self.make_server(provider)
        provider.release.set()

        response = self.dispatch(server, "live")

        self.assertIn("synthetic provider failure", response["error"]["message"])
        self.assert_summary_meta(self.dispatch(server, "live"), "live")
        self.assertEqual(provider.calls, {"live-model": 2})


if __name__ == "__main__":
    unittest.main()
